version: '3'
services:
  chain0: 
    image: sadfroghk/chain0
    container_name: chain0
    restart: unless-stopped
    command: bash /root/init.sh node
    ports:
      - 26656:26656
    environment:
      - MONIKER=YOURMONIKERNAME
